#!/usr/bin/env node
"use strict";

/**
 * Generates src/embeddedjs/modules/icons/codepoints.js from
 * src/embeddedjs/assets/icons.icomoon.json.
 *
 * Run via: npm run gen-icons
 *
 * @author    Cory Hughart <cory@coryhughart.com>
 * @copyright 2026 Cory Hughart
 * @license   https://www.gnu.org/licenses/gpl-3.0.html GPL-3.0-or-later
 * @link      https://cr0ybot.com/project/pebble-watchface-carbon
 */

const { readFileSync, writeFileSync, mkdirSync } = require("fs");
const { join, dirname } = require("path");

const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "src/embeddedjs/assets/icons.icomoon.json");
const OUT = join(ROOT, "src/embeddedjs/modules/icons/codepoints.js");

const { glyphs } = JSON.parse(readFileSync(SRC, "utf8"));

const toCamel = s => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const entries = glyphs
	.map(g => {
		const cp = g.extras.codePoint;
		// All icons are in the BMP Private Use Area (U+E000–U+F8FF), so a
		// simple \uXXXX escape is always valid.  Using a string literal instead
		// of String.fromCodePoint() at runtime means XS can bake the strings
		// into the XSA archive (flash/ROM) rather than allocating them in chunk RAM.
		const literal = `"\\u${cp.toString(16).toUpperCase().padStart(4, "0")}"`;
		return `\t${toCamel(g.extras.name)}: ${literal},`;
	})
	.join("\n");

const output = `\
// AUTO-GENERATED by scripts/gen-icons.js — do not edit by hand
// Source: src/embeddedjs/assets/icons.icomoon.json

const codepoints = {
${entries}
};

export default Object.freeze(codepoints);
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, output, "utf8");
console.log(`Generated ${glyphs.length} icons → ${OUT.replace(ROOT + "/", "")}`);
