#!/usr/bin/env node
"use strict";

/**
 * Generates src/embeddedjs/modules/icons/codepoints.js from
 * src/embeddedjs/assets/icons.icomoon.json.
 *
 * Run via: npm run gen-icons
 */

const { readFileSync, writeFileSync, mkdirSync } = require("fs");
const { join, dirname } = require("path");

const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "src/embeddedjs/assets/icons.icomoon.json");
const OUT = join(ROOT, "src/embeddedjs/modules/icons/codepoints.js");

const { glyphs } = JSON.parse(readFileSync(SRC, "utf8"));

const toCamel = s => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const entries = glyphs
	.map(g => `\t${toCamel(g.extras.name)}: String.fromCodePoint(${g.extras.codePoint}),`)
	.join("\n");

const output = `\
// AUTO-GENERATED by scripts/gen-icons.js — do not edit by hand
// Source: src/embeddedjs/assets/icons.icomoon.json

const codepoints = {
${entries}
};

export default Object.freeze(codepoints);
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, output, "utf8");
console.log(`Generated ${glyphs.length} icons → ${OUT.replace(ROOT + "/", "")}`);
